"""Add member_since to User model

Revision ID: 93860582aa2a
Revises: 
Create Date: 2024-07-11 14:14:30.552152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93860582aa2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_since', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('member_since')

    # ### end Alembic commands ###
